import type { ThemeDefinition } from '../types'

export const amethystTheme: ThemeDefinition = {
  id: 'amethyst',
  name: 'Amethyst',
  description: 'Purple-toned professional theme',
  author: 'Dojo Team',
  previewColors: {
    primary: '#9d5ac7',
    secondary: '#dfc1ea',
    accent: '#ff9cb5'
  },
  light: {
    background: '#faf7fc',
    foreground: '#3f2d4d',
    card: '#ffffff',
    cardForeground: '#3f2d4d',
    popover: '#ffffff',
    popoverForeground: '#3f2d4d',
    primary: '#9d5ac7',
    primaryForeground: '#faf7fc',
    secondary: '#e6d4ef',
    secondaryForeground: '#3f2d4d',
    muted: '#e5d2e6',
    mutedForeground: '#60477a',
    accent: '#ff9cb5',
    accentForeground: '#3d2638',
    destructive: '#e84855',
    destructiveForeground: '#faf7fc',
    success: '#16A34A',
    successForeground: '#FFFFFF',
    border: '#d5c3df',
    input: '#ede3f4',
    ring: '#9d5ac7',
    chart1: '#9d5ac7',
    chart2: '#ff9cb5',
    chart3: '#52d681',
    chart4: '#ffdb7d',
    chart5: '#a89eff',
    sidebar: '#f3ecf8',
    sidebarForeground: '#3f2d4d',
    sidebarPrimary: '#9d5ac7',
    sidebarPrimaryForeground: '#faf7fc',
    sidebarAccent: '#ff9cb5',
    sidebarAccentForeground: '#3d2638',
    sidebarBorder: '#dccee5',
    sidebarRing: '#9d5ac7',
    serviceBg: '#faf7fc'
  },
  dark: {
    background: '#1a1622',
    foreground: '#e6dced',
    card: '#231f2e',
    cardForeground: '#e6dced',
    popover: '#231f2e',
    popoverForeground: '#e6dced',
    primary: '#b77dd8',
    primaryForeground: '#1a1622',
    secondary: '#50426b',
    secondaryForeground: '#e6dced',
    muted: '#2c2537',
    mutedForeground: '#b0a1c1',
    accent: '#3e3350',
    accentForeground: '#ddb4d0',
    destructive: '#c95762',
    destructiveForeground: '#1a1622',
    success: '#52d681',
    successForeground: '#1a1622',
    border: '#332c42',
    input: '#292433',
    ring: '#b77dd8',
    chart1: '#b77dd8',
    chart2: '#ddb4d0',
    chart3: '#52d681',
    chart4: '#ffdb7d',
    chart5: '#a89eff',
    sidebar: '#151320',
    sidebarForeground: '#e6dced',
    sidebarPrimary: '#b77dd8',
    sidebarPrimaryForeground: '#1a1622',
    sidebarAccent: '#3e3350',
    sidebarAccentForeground: '#ddb4d0',
    sidebarBorder: '#292433',
    sidebarRing: '#b77dd8',
    serviceBg: '#1a1622'
  }
}