TEST_FILE_TIERS = {
    "test_accounts.py": "contract",
    "test_auth.py": "semantic",
    "test_authz_matrix.py": "contract",
    "test_awards.py": "semantic",
    "test_background_stats.py": "integration",
    "test_belts.py": "semantic",
    "test_challenges.py": "semantic",
    "test_client_flows.py": "semantic",
    "test_course.py": "semantic",
    "test_crew_scoreboard.py": "semantic",
    "test_data_model.py": "integration",
    "test_dojo_admin_api.py": "contract",
    "test_dojo_cli.py": "integration",
    "test_dojo_pages.py": "contract",
    "test_dojo_spec.py": "contract",
    "test_dojos.py": "semantic",
    "test_edit_links.py": "semantic",
    "test_error_handler.py": "integration",
    "test_feed.py": "semantic",
    "test_feed_search.py": "semantic",
    "test_hidden_profile.py": "semantic",
    "test_integrations.py": "semantic",
    "test_middleware.py": "integration",
    "test_module_resources.py": "semantic",
    "test_multinode.py": "semantic",
    "test_playwright_mcp.py": "semantic",
    "test_query_timer.py": "integration",
    "test_scoreboard.py": "contract",
    "test_scoreboard_api.py": "contract",
    "test_search.py": "semantic",
    "test_side_integrations.py": "semantic",
    "test_solves.py": "semantic",
    "test_ssh.py": "semantic",
    "test_ssh_semantics.py": "semantic",
    "test_surveys.py": "semantic",
    "test_theme_assets.py": "integration",
    "test_visibility.py": "semantic",
    "test_visibility_matrix.py": "semantic",
    "test_welcome.py": "semantic",
    "test_worker_events.py": "integration",
    "test_workspace_api.py": "semantic",
    "test_workspace_proxy.py": "contract",
    "test_workspace_runtime.py": "integration",
}

TEST_TIER_OVERRIDES = {
    "test_background_stats.py::test_should_daily_restart": "unit",
    "test_background_stats.py::test_get_message_timestamp": "unit",
    "test_background_stats.py::test_is_event_stale_logic": "unit",
    "test_background_stats.py::test_dojo_specific_scores_update_only_updates_target_dojo": "unit",
    "test_background_stats.py::test_scores_update_deleted_dojo_skips_gracefully": "unit",
    "test_background_stats.py::test_scores_update_empty_payload_updates_all_dojos": "unit",
    "test_background_stats.py::test_publish_scores_event_with_dojo_id": "unit",
    "test_background_stats.py::test_publish_scores_event_without_dojo_id": "unit",
    "test_background_stats.py::test_challenge_solves_uses_string_keys": "unit",
    "test_client_flows.py::test_container_counts_track_container_lifecycle": "integration",
    "test_client_flows.py::test_stat_dashboard_payload_shape": "integration",
    "test_crew_scoreboard.py::test_crew_parse_and_aggregation_unit": "unit",
    "test_feed_search.py::test_feed_ttl_prunes_expired_events": "integration",
    "test_feed_search.py::test_feed_publishing_trims_to_max_events": "integration",
    "test_feed_search.py::test_feed_events_empty_store": "integration",
    "test_feed_search.py::test_feed_page_bootstraps_the_newest_twenty_events": "integration",
    "test_feed_search.py::test_activity_cache_miss_recomputes_and_repopulates": "integration",
    "test_feed_search.py::test_activity_only_counts_the_last_365_days": "integration",
    "test_feed_search.py::test_activity_counts_private_dojo_solves": "integration",
    "test_feed_search.py::test_activity_total_matches_db_after_cache_loss": "integration",
    "test_feed_search.py::test_activity_worker_recomputes_on_activity_update_event": "integration",
    "test_feed_search.py::test_activity_worker_ignores_malformed_events": "integration",
    "test_feed_search.py::test_activity_worker_skips_stale_events": "integration",
    "test_scoreboard_api.py::test_scoreboard_challenge_solve_counts": "integration",
    "test_scoreboard_api.py::test_scores_cache_written_for_public_dojo": "integration",
    "test_scoreboard_api.py::test_scoreboard_cache_miss_returns_empty": "integration",
    "test_scoreboard_api.py::test_queued_solve_events_are_not_dropped": "integration",
    "test_worker_events.py::test_queued_stat_events_defer_until_after_request": "unit",
    "test_worker_events.py::test_publish_stat_event_swallows_redis_errors": "unit",
    "test_worker_events.py::test_handler_registry_covers_published_event_types": "unit",
    "test_worker_events.py::test_daily_restart_exits_consume_loop": "unit",
    "test_worker_events.py::test_container_stats_handler_error_preserves_cache": "unit",
    "test_worker_events.py::test_image_pull_handler_skips_without_docker": "unit",
    "test_workspace_proxy.py::test_workspace_system_mounts_are_read_only": "integration",
}

MULTINODE_TEST_FILES = {
    "test_multinode.py",
    "test_ssh_semantics.py",
    "test_workspace_api.py",
    "test_workspace_runtime.py",
}

MULTINODE_TESTS = {
    "test_challenges.py::test_workspace_auto_start_without_home_mount",
    "test_dojo_cli.py::test_enter_finds_container_on_worker_node",
    "test_dojo_cli.py::test_compose_selects_profiles_by_node_role",
    "test_dojo_cli.py::test_startup_gates_are_satisfied",
    "test_dojo_cli.py::test_wait_succeeds_on_healthy_dojo",
    "test_dojo_cli.py::test_wait_skips_stats_gate_on_worker",
    "test_dojo_cli.py::test_node_mutation_denied_on_worker",
    "test_dojo_cli.py::test_node_refresh_worker_daemon_json_idempotent",
    "test_dojo_cli.py::test_watchdog_sweeps_every_daemon_hosting_user_containers",
}
