TEST_FILE_TIERS = {
    "test_watchdog_images.py": "unit",
    "test_watchdog_containers.py": "unit",
    "test_accounts.py": "contract",
    "test_auth.py": "semantic",
    "test_authz_matrix.py": "contract",
    "test_awards.py": "semantic",
    "test_background_stats.py": "integration",
    "test_challenges.py": "semantic",
    "test_client_flows.py": "semantic",
    "test_client_semantics.py": "semantic",
    "test_course.py": "semantic",
    "test_crew_scoreboard.py": "semantic",
    "test_dojo_admin_api.py": "contract",
    "test_dojo_cli.py": "integration",
    "test_dojo_spec.py": "contract",
    "test_dojos.py": "semantic",
    "test_edit_links.py": "semantic",
    "test_error_handler.py": "integration",
    "test_feed_search.py": "semantic",
    "test_frontend_semantics.py": "semantic",
    "test_hidden_profile.py": "semantic",
    "test_homefs_semantics.py": "semantic",
    "test_integrations.py": "semantic",
    "test_image_distribution.py": "semantic",
    "test_llm.py": "semantic",
    "test_mac_workspace.py": "semantic",
    "test_middleware.py": "integration",
    "test_module_resources.py": "semantic",
    "test_multinode.py": "semantic",
    "test_profile.py": "semantic",
    "test_query_timer.py": "integration",
    "test_scoreboard_api.py": "contract",
    "test_settings_page.py": "semantic",
    "test_side_integrations.py": "semantic",
    "test_solves.py": "semantic",
    "test_ssh_semantics.py": "semantic",
    "test_surveys.py": "semantic",
    "test_theme_assets.py": "integration",
    "test_visibility.py": "semantic",
    "test_visibility_matrix.py": "semantic",
    "test_welcome.py": "semantic",
    "test_worker_events.py": "integration",
    "test_workspace_api.py": "semantic",
    "test_workspace_proxy.py": "contract",
    "test_workspace_runtime.py": "integration",
    "test_workspace_tui.py": "semantic",
    "test_workspace_llm.py": "semantic",
}

TEST_TIER_OVERRIDES = {
    "test_accounts.py::test_api_registration_profile_fields_persist_and_can_be_updated": "semantic",
    "test_accounts.py::test_api_registration_respects_allowed_email_domains": "semantic",
    "test_accounts.py::test_api_registration_with_mail_waits_for_email_confirmation": "semantic",
    "test_accounts.py::test_api_password_recovery_with_mail_preserves_oauth_accounts": "semantic",
    "test_accounts.py::test_verified_email_gate_blocks_actions": "semantic",
    "test_accounts.py::test_html_register_with_mail_requires_confirmation": "semantic",
    "test_accounts.py::test_user_token_lifecycle": "semantic",
    "test_accounts.py::test_notification_email_delivery_and_failure": "semantic",
    "test_accounts.py::test_banned_user_with_api_token_is_forbidden": "semantic",
    "test_accounts.py::test_self_email_change_resets_verified_and_enforces_whitelist": "semantic",
    "test_dojo_admin_api.py::test_solves_exports_preserve_order_identity_and_timestamps": "semantic",
    "test_dojo_spec.py::test_reordering_modules_and_resources_preserves_learner_progress": "semantic",
    "test_dojo_spec.py::test_dojo_level_import_inherits_source_fields": "semantic",
    "test_dojo_spec.py::test_inherited_modules_preserve_challenge_controls": "semantic",
    "test_dojo_spec.py::test_transferring_a_challenge_preserves_prior_solves_across_updates": "semantic",
    "test_dojo_spec.py::test_personal_downloads_serve_the_requesting_users_file": "semantic",
    "test_workspace_proxy.py::test_workspace_proxy_preserves_application_requests_and_responses": "semantic",
    "test_workspace_runtime.py::test_dojo_service_recovers_stale_pid_files_and_stops_gracefully": "semantic",
    "test_background_stats.py::test_should_daily_restart": "unit",
    "test_background_stats.py::test_get_message_timestamp": "unit",
    "test_background_stats.py::test_is_event_stale_logic": "unit",
    "test_background_stats.py::test_dojo_specific_scores_update_only_updates_target_dojo": "unit",
    "test_background_stats.py::test_scores_update_deleted_dojo_skips_gracefully": "unit",
    "test_background_stats.py::test_scores_update_empty_payload_updates_all_dojos": "unit",
    "test_background_stats.py::test_publish_scores_event_with_dojo_id": "unit",
    "test_background_stats.py::test_publish_scores_event_without_dojo_id": "unit",
    "test_background_stats.py::test_challenge_solves_uses_string_keys": "unit",
    "test_crew_scoreboard.py::test_crew_parse_and_aggregation_unit": "unit",
    "test_dojo_cli.py::test_deploy_discord_secret_scope": "unit",
    "test_dojo_cli.py::test_wait_reports_workspace_builder_exit_status": "unit",
    "test_dojo_cli.py::test_cloud_backup_encrypts_recent_archives_and_reports_upload_failure": "unit",
    "test_scoreboard_api.py::test_queued_solve_events_are_not_dropped": "integration",
    "test_workspace_proxy.py::test_workspace_system_mounts_are_read_only": "integration",
}

MULTINODE_TESTS = {
    "test_challenges.py::test_workspace_auto_start_without_home_mount",
    "test_challenges.py::test_workspace_restart_preserves_home_mount",
    "test_challenges.py::test_workspace_home_option_ignores_image_volume",
    "test_dojo_cli.py::test_enter_finds_container_on_worker_node",
    "test_dojo_cli.py::test_compose_selects_profiles_by_node_role",
    "test_dojo_cli.py::test_startup_gates_are_satisfied",
    "test_dojo_cli.py::test_wait_succeeds_on_healthy_dojo",
    "test_dojo_cli.py::test_wait_skips_stats_gate_on_worker",
    "test_dojo_cli.py::test_node_mutation_denied_on_worker",
    "test_dojo_cli.py::test_node_refresh_worker_daemon_json_idempotent",
    "test_dojo_cli.py::test_watchdog_sweeps_every_daemon_hosting_user_containers",
    "test_dojo_cli.py::test_watchdog_prunes_unreferenced_images",
    "test_homefs_semantics.py::test_multinode_homes_are_lazy_worker_local_btrfs_volumes",
    "test_homefs_semantics.py::test_multinode_home_quota_is_enforced_on_owning_worker",
    "test_homefs_semantics.py::test_multinode_home_persists_and_snapshots_through_coordinator",
    "test_homefs_semantics.py::test_multinode_cross_node_overlay_is_current_isolated_and_ephemeral",
    "test_homefs_semantics.py::test_multinode_coordinator_rejects_competing_active_host",
    "test_multinode.py::test_multinode_container_placement",
    "test_ssh_semantics.py::test_commands_run_in_the_workspace_not_the_sshd_container",
    "test_ssh_semantics.py::test_interactive_ssh_reconnects_when_the_challenge_is_replaced",
    "test_ssh_semantics.py::test_sftp_transfer_round_trips",
    "test_ssh_semantics.py::test_scp_transfer_round_trips",
    "test_workspace_api.py::test_starting_a_challenge_replaces_the_previous_container",
    "test_workspace_api.py::test_workspace_token_impersonates_its_owner",
    "test_workspace_api.py::test_net_admin_capability_requires_the_dojo_permission",
    "test_workspace_api.py::test_kata_workspace_internet_dns_and_https",
    "test_workspace_runtime.py::test_workspace_profile_symlink_farm_exposes_the_toolchain",
    "test_workspace_runtime.py::test_terminal_service_contract",
    "test_workspace_runtime.py::test_workspace_proxy_signature_covers_the_container_and_port",
    "test_workspace_runtime.py::test_nginx_routes_by_host_header",
    "test_workspace_proxy.py::test_workspace_proxy_preserves_application_requests_and_responses",
}
