TEST_FILE_TIERS = {
    "test_accounts.py": "contract",
    "test_auth.py": "semantic",
    "test_authz_matrix.py": "contract",
    "test_awards.py": "semantic",
    "test_background_stats.py": "integration",
    "test_challenges.py": "semantic",
    "test_client_flows.py": "semantic",
    "test_course.py": "semantic",
    "test_crew_scoreboard.py": "semantic",
    "test_dojo_admin_api.py": "contract",
    "test_dojo_cli.py": "integration",
    "test_dojo_spec.py": "contract",
    "test_dojos.py": "semantic",
    "test_edit_links.py": "semantic",
    "test_error_handler.py": "integration",
    "test_feed_search.py": "semantic",
    "test_hidden_profile.py": "semantic",
    "test_integrations.py": "semantic",
    "test_middleware.py": "integration",
    "test_module_resources.py": "semantic",
    "test_multinode.py": "semantic",
    "test_query_timer.py": "integration",
    "test_scoreboard_api.py": "contract",
    "test_side_integrations.py": "semantic",
    "test_solves.py": "semantic",
    "test_ssh_semantics.py": "semantic",
    "test_surveys.py": "semantic",
    "test_theme_assets.py": "integration",
    "test_visibility.py": "semantic",
    "test_visibility_matrix.py": "semantic",
    "test_welcome.py": "semantic",
    "test_worker_events.py": "integration",
    "test_workspace_api.py": "semantic",
    "test_workspace_proxy.py": "contract",
    "test_workspace_runtime.py": "integration",
}

TEST_TIER_OVERRIDES = {
    "test_background_stats.py::test_should_daily_restart": "unit",
    "test_background_stats.py::test_get_message_timestamp": "unit",
    "test_background_stats.py::test_is_event_stale_logic": "unit",
    "test_background_stats.py::test_dojo_specific_scores_update_only_updates_target_dojo": "unit",
    "test_background_stats.py::test_scores_update_deleted_dojo_skips_gracefully": "unit",
    "test_background_stats.py::test_scores_update_empty_payload_updates_all_dojos": "unit",
    "test_background_stats.py::test_publish_scores_event_with_dojo_id": "unit",
    "test_background_stats.py::test_publish_scores_event_without_dojo_id": "unit",
    "test_background_stats.py::test_challenge_solves_uses_string_keys": "unit",
    "test_crew_scoreboard.py::test_crew_parse_and_aggregation_unit": "unit",
    "test_dojo_cli.py::test_deploy_discord_secret_scope": "unit",
    "test_scoreboard_api.py::test_queued_solve_events_are_not_dropped": "integration",
    "test_workspace_proxy.py::test_workspace_system_mounts_are_read_only": "integration",
}

MULTINODE_TESTS = {
    "test_challenges.py::test_workspace_auto_start_without_home_mount",
    "test_dojo_cli.py::test_enter_finds_container_on_worker_node",
    "test_dojo_cli.py::test_compose_selects_profiles_by_node_role",
    "test_dojo_cli.py::test_startup_gates_are_satisfied",
    "test_dojo_cli.py::test_wait_succeeds_on_healthy_dojo",
    "test_dojo_cli.py::test_wait_skips_stats_gate_on_worker",
    "test_dojo_cli.py::test_node_mutation_denied_on_worker",
    "test_dojo_cli.py::test_node_refresh_worker_daemon_json_idempotent",
    "test_dojo_cli.py::test_watchdog_sweeps_every_daemon_hosting_user_containers",
    "test_multinode.py::test_multinode_container_placement",
    "test_ssh_semantics.py::test_commands_run_in_the_workspace_not_the_sshd_container",
    "test_ssh_semantics.py::test_sftp_transfer_round_trips",
    "test_ssh_semantics.py::test_scp_transfer_round_trips",
    "test_workspace_api.py::test_starting_a_challenge_replaces_the_previous_container",
    "test_workspace_api.py::test_workspace_token_impersonates_its_owner",
    "test_workspace_api.py::test_net_admin_capability_requires_the_dojo_permission",
    "test_workspace_runtime.py::test_workspace_profile_symlink_farm_exposes_the_toolchain",
    "test_workspace_runtime.py::test_terminal_service_contract",
    "test_workspace_runtime.py::test_workspace_proxy_signature_covers_the_container_and_port",
    "test_workspace_runtime.py::test_nginx_routes_by_host_header",
}
