#!/bin/sh

error () {
    echo "Error: $1" >&2
    exit 1
}

export VSCODE_CLI_DATA_DIR=/data/vscode

git checkout $(git for-each-ref --format='%(refname:lstrip=2)' refs/heads --points-at HEAD | head -n1) 2>/dev/null || error "Failed to checkout branch"
git -C /opt/pwn.college checkout "$(git for-each-ref --format='%(refname:short) %(objectname)' refs/heads | awk -v head=$(git rev-parse HEAD) '$2==head{print $1; exit}')"

if code tunnel user show >/dev/null 2>&1; then
    echo "[-] VSCode tunnel is already authenticated" >&2
else
    echo "[-] Authenticating with VSCode tunnel" >&2
    trap 'echo "[-] Authentication interrupted"; exit 1' INT TERM
    while true; do
        code tunnel user login --provider github
        code tunnel user show >/dev/null && {
            break
        }
        echo "[-] Authentication failed, retrying..." >&2
    done
    trap - INT TERM
    echo "[+] Authentication successful" >&2
fi

install -d -m 700 /data/vscode
printf 'dojo-%s\n' "$HOSTNAME" > /data/vscode/tunnel-name
if ! systemctl is-active --quiet vscode-tunnel; then
    systemctl start vscode-tunnel || error "Failed to start VSCode tunnel service."
    echo "[+] VSCode tunnel service started successfully" >&2
else
    echo "[-] VSCode tunnel service is already running" >&2
fi

systemctl --no-pager status vscode-tunnel

echo "[+] Setup complete"
echo "[-] Access your VSCode instance at: https://vscode.dev/tunnel/dojo-$HOSTNAME/opt/pwn.college"
