#!/bin/sh

[ -f /tmp/.dojo/vnc/websockify-windows.pid ] && exit
exec 2> /tmp/.dojo/service-desktop-windows.log

mkdir -p /tmp/.dojo/vnc /home/hacker/.vnc
start-stop-daemon --start \
                  --pidfile /tmp/.dojo/vnc/websockify-windows.pid \
                  --make-pidfile \
                  --background \
                  --no-close \
                  --startas /usr/bin/websockify \
                  -- \
                  --web /usr/share/novnc/ \
                  dojo-user:6082 \
                  localhost:5912 \
                  </dev/null \
                  >>/tmp/.dojo/vnc/websockify-windows.log \
                  2>&1

until curl -s dojo-user:6082 >/dev/null; do sleep 0.1; done
