splunk:
  accept_license: true
  password: DojoSplunk2024!
  hec:
    enable: true
    ssl: false
    port: 8088
    token: "11111111-1111-1111-1111-111111111111"
  conf:
    - key: server
      value:
        license: /tmp/Splunk.License
    - key: web
      value:
        settings:
          enableSplunkWebSSL: false
    - key: limits
      value:
        kv:
          maxKVSize: 8192
    - key: server
      value:
        general:
          serverName: dojo-splunk