server {
    include /etc/nginx/conf.d/future-dojo-host.conf;
    listen 80;

    location ^~ /api/ {
        proxy_pass http://ctfd_upstream;
        include /etc/nginx/conf.d/proxy-headers.conf;
    }

    location ^~ /pwncollege_api/ {
        proxy_pass http://ctfd_upstream;
        include /etc/nginx/conf.d/proxy-headers.conf;
    }

    location / {
        proxy_pass http://frontend_upstream;
        include /etc/nginx/conf.d/proxy-headers.conf;
    }
}
