server {
    include /etc/nginx/conf.d/workspace.conf;
    listen 80;

    location ^~ /.well-known/acme-challenge/ {
        root /run/dojo/acme;
    }

    location / {
        return 307 https://$host$request_uri;
    }
}
