server {
    include /etc/nginx/conf.d/workspace.conf;
    listen 80;
    access_log /var/log/nginx/access.log workspace;
    error_log /dev/null;

    location ^~ / {
        return 307 https://$host$request_uri;
    }
}
