#!/bin/sh

cd /opt/pwn.college

ACTION="$1"
shift

case "$ACTION" in
    "enter")
        CONTAINER="user_$1"
        shift
        if [ -n "$USER" ]; then
            docker exec -it "$CONTAINER" bash
        else
            docker exec -it --user="$USER" "$CONTAINER" bash
        fi
        ;;

    "compose")
        docker compose --env-file=/opt/pwn.college/data/config.env $@
        ;;

    "shell")
        docker exec -it ctfd python manage.py shell
        ;;

    "db")
        docker exec -it ctfd_db mysql -pctfd -Dctfd
        ;;

    "backup")
        docker exec ctfd_db mysqldump -pctfd --single-transaction --routines --triggers ctfd > "/tmp/db-backup-$(date -Iseconds).sql"
        ;;

    "logs")
        journalctl -u pwn.college -f
        ;;

    "restart")
        for cmd in 'build ctfd' 'kill ctfd' 'rm -f ctfd' 'up -d ctfd' 'logs -f ctfd'; do
            docker compose --env-file=/opt/pwn.college/data/config.env $cmd;
        done
        ;;

esac
