#!/opt/pwn.college/python

import os
import sys
import socket
import subprocess
import time
import grp
import argparse
from pathlib import Path

# /run is not world writeable. this should prevent race conditions.
STATEFUL_PATH = Path("/run/windows")
IMAGE_PATH = STATEFUL_PATH / "windows.qcow2"
STATEFUL_WORLD_WRITEABLE_PATH = STATEFUL_PATH / "world-writeable"
virtfs_sock_path = lambda dir_path, tag: dir_path / f"virtfs-{tag}.sock"
FLAG_SHARE_PATH = STATEFUL_PATH / "flag-volume"
# these much match dojo-service
RUN_DIR = Path("/run/dojo/var")
service_log_path = lambda service_name: RUN_DIR / f"{service_name}.log"
SERVICES = set((
    "windows-vm",
    "windows-virtfs-challenge",
    "windows-virtfs-home",
    "windows-virtfs-flag"
))

VIRTIOFSD_PATH = "@virtiofsd@/bin/virtiofsd"
QEMU_SYSTEM_X86_PATH = "@qemu@/bin/qemu-system-x86_64"
QEMU_IMG_PATH = "@qemu@/bin/qemu-img"
SSH_PATH = "@openssh@/bin/ssh"
TAIL_PATH = "@coreutils@/bin/tail"
DOJO_SERVICE_PATH = "@dojo-service@/bin/dojo-service"
WINDOWS_BASE_PATH = "@windows-vm@/windows-base.qcow2"
VIRTIO_DRIVERS_PATH = "@virtio-win-drivers@/share/virtio-drivers.iso"
SETUP_DRIVE_PATH = "@setup-drive@"
SERVER_ISO_PATH = "@server-iso@"


def error(msg):
    print(msg, file=sys.stderr)
    exit(1)


def initialize():
    os.setegid(os.geteuid())
    try:
        STATEFUL_PATH.mkdir()
    except FileExistsError:
        pass
    try:
        STATEFUL_WORLD_WRITEABLE_PATH.mkdir()
    except FileExistsError:
        pass
    STATEFUL_WORLD_WRITEABLE_PATH.chmod(0o777)
    try:
        FLAG_SHARE_PATH.mkdir()
    except FileExistsError:
        pass


def vm_hostname():
    with open("/etc/hosts") as f:
        if "127.0.0.1\tvm" in f.read():
            return "vm"
        else:
            return "127.0.0.1"


def is_privileged():
    groups = set(grp.getgrgid(group).gr_name for group in os.getgroups())
    return os.getuid() == 0 or "sudo" in groups


def execve(argv):
    os.seteuid(os.getuid())
    os.setegid(os.getgid())
    os.execve(argv[0], argv, os.environ)


def start_daemon(service_name, child_argv, drop_privs=False):
    def preexec_drop_privs():
        os.seteuid(os.getuid())
        os.setegid(os.getgid())

    preexec_fn = None
    if drop_privs:
        preexec_fn = preexec_drop_privs

    assert service_name in SERVICES, f"starting a service which we will fail to clean up later!"
    daemon_argv = [
        DOJO_SERVICE_PATH,
        "start",
        service_name,
    ] + child_argv

    subprocess.run(
        daemon_argv,
        stdin=subprocess.DEVNULL,
        stdout=subprocess.DEVNULL,
        stderr=subprocess.STDOUT,
        check=True,
        preexec_fn=preexec_fn,
    )


def reset_image():
    try:
        IMAGE_PATH.unlink()
    except FileNotFoundError:
        pass

    subprocess.check_call(
        [
            QEMU_IMG_PATH,
            "create",
            "-f",
            "qcow2",
            "-o",
            f"backing_file={WINDOWS_BASE_PATH}",
            "-o",
            "backing_fmt=qcow2",
            str(IMAGE_PATH),
            "51200M",
        ],
        stdin=subprocess.DEVNULL,
        stdout=sys.stdout,
        stderr=sys.stderr,
    )


def kill():
    for service_name in SERVICES:
        argv = [
            DOJO_SERVICE_PATH,
            "kill",
            service_name
        ]

        subprocess.run(
            argv,
            stdin=subprocess.DEVNULL,
            stdout=subprocess.DEVNULL,
            stderr=subprocess.STDOUT,
            check=True,
        )

        try:
            service_log_path(service_name).unlink()
        except (OSError, FileNotFoundError):
            pass


def fs_bridge_running():
    procfs = Path("/proc")
    pid_dirs = [d for d in procfs.iterdir() if d.name.isdigit()]
    for pid in pid_dirs:
        try:
            exe_link = Path("/proc") / str(pid) / "exe"
            if os.readlink(str(exe_link)) == str(VIRTIOFSD_PATH):
                return True
        except FileNotFoundError:
            pass
    return False


def start():
    if not Path("/dev/kvm").exists():
        raise NotImplementedError(
            "Running the windows VM without KVM is not implemented"
        )

    if not IMAGE_PATH.exists():
        reset_image()

    # We need to pass the flag into the VM for the initial boot, before the FS bridge
    #  starts.
    # The FS bridge lets an unprivileged Windows user access the shared filesystem with
    #  root privileges, so it would be quite bad if we were to set up the flag again.
    # This function gets called even if the VM is already running, so we need to make
    #  sure the bridge isn't running.
    if not fs_bridge_running():
        with open("/flag", "r") as f:
            flag = f.read()
        fd = os.open(
            path=str(FLAG_SHARE_PATH / "flag"),
            flags=(os.O_WRONLY | os.O_CREAT | os.O_TRUNC),
            mode=0o600
        )
        os.fchmod(fd, 0o600)
        with open(fd, "w") as f:
            f.write(flag)

    if is_privileged():
        (FLAG_SHARE_PATH / "practice-mode-enabled").touch()

    mem = "2048M"
    # fmt: off
    qemu_argv = [
        QEMU_SYSTEM_X86_PATH,
        "-name", "dojo",
        "-boot", "once=d",
        "-machine", "type=pc,accel=kvm",
        "-m", mem,
        "-smp", "4",
        "-display", "none",
        "-nographic",
        "-device", "virtio-net,netdev=user.0",
        # 5985: WinRM, 22: SSH, 5912: VNC, 4001: ChallengeProxy
        "-netdev", "user,id=user.0,hostfwd=tcp::5985-:5985,hostfwd=tcp::22-:22,hostfwd=tcp::5912-:5912,hostfwd=tcp::4001-:4001",
        "-serial", "null",
        "-monitor", "none",
        "-drive", f"file={SETUP_DRIVE_PATH},read-only=on,format=raw,index=0,if=floppy",
        "-drive", f"file={SERVER_ISO_PATH},read-only=on,media=cdrom,index=1",
        "-drive", f"file={VIRTIO_DRIVERS_PATH},read-only=on,media=cdrom,index=2",
        "-drive", f"file={IMAGE_PATH},if=virtio,cache=writeback,discard=ignore,format=qcow2,index=3",
        "-object", f"memory-backend-memfd,id=mem,size={mem},share=on",
        "-numa", "node,memdev=mem"
    ]
    # fmt: on
    mounts = {
        "challenge": ("/challenge", False),
        "home": ("/home/hacker", False),
        "flag": (str(FLAG_SHARE_PATH), True)
    }
    for tag, (mountpoint, needs_root) in mounts.items():
        dir_path = STATEFUL_PATH if needs_root else STATEFUL_WORLD_WRITEABLE_PATH
        sock_path = virtfs_sock_path(dir_path, tag)
        start_daemon(
            f"windows-virtfs-{tag}",
            # fmt: off
            [
                str(VIRTIOFSD_PATH),
                "--writeback",
                "--socket-path", str(sock_path),
                "--sandbox", "chroot" if needs_root else "none",
                "--shared-dir", str(mountpoint)
            ],
            # fmt: on
            drop_privs=not needs_root
        )

        # fmt: off
        qemu_argv += [
            "-chardev", f"socket,id={tag}-sock,path={sock_path}",
            "-device", f"vhost-user-fs-pci,queue-size=1024,chardev={tag}-sock,tag={tag}",
        ]
        # fmt: on

    start_daemon("windows-vm", qemu_argv)


def wait():
    for _ in range(50):
        try:
            connection = socket.create_connection((vm_hostname(), 22), timeout=30)
            data = connection.recv(3)
            connection.close()
            if data == b"SSH":
                break
        except (ConnectionRefusedError, socket.timeout):
            pass
        time.sleep(0.1)
    else:
        error("Error: could not connect to vm!")


def connect():
    wait()
    execve([SSH_PATH, vm_hostname()])


def exec_(*args):
    wait()
    if sys.stdout.isatty():
        execve([SSH_PATH, "-t", vm_hostname(), "--", *args])
    else:
        execve([SSH_PATH, vm_hostname(), "--", *args])


def logs():
    argv = [
        TAIL_PATH,
        "-F",
        "-n+1",
        str(VM_LOGFILE),
    ]

    while True:
        subprocess.run(argv, stdin=subprocess.DEVNULL, stderr=subprocess.DEVNULL)

        time.sleep(0.1)


def main():
    global args

    initialize()

    parser = argparse.ArgumentParser()
    subparsers = parser.add_subparsers(dest="command", required=True)

    connect_parser = subparsers.add_parser("connect", help="connect to vm")

    exec_parser = subparsers.add_parser("exec", help="exec command in vm")
    exec_parser.add_argument("exec_command")
    exec_parser.add_argument("exec_command_args", nargs=argparse.REMAINDER)

    start_parser = subparsers.add_parser("start", help="start vm")

    stop_parser = subparsers.add_parser("stop", help="stop vm")

    kill_parser = subparsers.add_parser("kill", help="kill vm")

    restart_parser = subparsers.add_parser("restart", help="restart vm")

    forcerestart_parser = subparsers.add_parser(
        "forcerestart", help="kill and restart vm"
    )

    reset_parser = subparsers.add_parser("reset", help="reset VM image")

    args = parser.parse_args()

    commands = {
        "connect": lambda: (start(), connect()),
        "exec": lambda: (start(), exec_(args.exec_command, *args.exec_command_args)),
        "start": lambda: (kill(), start()),
        "stop": lambda: exec_("powershell", "-command", "stop-computer -force"),
        "kill": lambda: kill(),
        "restart": lambda: exec_("powershell", "-command", "restart-computer -force"),
        "forcerestart": lambda: (kill(), start()),
        "reset": lambda: reset_image(),
    }

    try:
        commands[args.command]()
    except KeyboardInterrupt:
        pass


if __name__ == "__main__":
    main()
