#!/opt/pwn.college/python

import os
import sys
import socket
import subprocess
import time
import grp
import argparse


def initialize():
    os.setegid(os.geteuid())
    try:
        os.mkdir("/tmp/kernel")
    except FileExistsError:
        pass


def is_practice():
    return "sudo" in [grp.getgrgid(g).gr_name for g in os.getgroups()]


def execve(argv):
    os.seteuid(os.getuid())
    os.setegid(os.getgid())
    os.execve(argv[0], argv, os.environ)


def start():
    qemu_argv = [
        "/usr/bin/qemu-system-x86_64",
        "-kernel", "/opt/linux/bzImage",
        "-fsdev", "local,id=rootfs,path=/,security_model=passthrough",
        "-device", "virtio-9p-pci,fsdev=rootfs,mount_tag=/dev/root",
        "-fsdev", "local,id=homefs,path=/home/hacker,security_model=passthrough",
        "-device", "virtio-9p-pci,fsdev=homefs,mount_tag=/home/hacker",
        "-device", "e1000,netdev=net0",
        "-netdev", "user,id=net0,hostfwd=tcp::22-:22",
        "-m", "2G",
        "-smp", "2",
        "-nographic",
        "-monitor", "none",
        "-append", "rw rootfstype=9p rootflags=trans=virtio console=ttyS0 init=/opt/pwn.college/kernel/init nokaslr",
    ]

    if is_practice():
        qemu_argv.append("-s")

    argv = [
        "/usr/sbin/start-stop-daemon",
        "--start",
        "--pidfile", "/tmp/kernel/kernel.pid",
        "--make-pidfile",
        "--background",
        "--no-close",
        "--quiet",
        "--startas", qemu_argv[0],
        "--",
        *qemu_argv[1:]
    ]

    subprocess.run(argv,
                   stdin=subprocess.DEVNULL,
                   stdout=open("/tmp/kernel/kernel.log", "a"),
                   stderr=subprocess.STDOUT)


def stop():
    argv = [
        "/usr/sbin/start-stop-daemon",
        "--stop",
        "--pidfile", "/tmp/kernel/kernel.pid",
        "--remove-pidfile",
        "--quiet",
    ]

    subprocess.run(argv,
                   stdin=subprocess.DEVNULL,
                   stdout=open("/tmp/kernel/kernel.log", "a"),
                   stderr=subprocess.STDOUT)


def connect():
    for _ in range(50):
        try:
            connection = socket.create_connection(("kernel", 22), timeout=30)
        except ConnectionRefusedError:
            pass
        else:
            data = connection.recv(3)
            connection.close()
            if data == b"SSH":
                break
        time.sleep(0.1)
    else:
        print("Error: could not connect to kernel!", file=sys.stderr)
        exit(1)

    execve(["/usr/bin/ssh", "kernel"])


def debug():
    if not is_practice():
        print("Error: kernel can only be debugged in practice mode!", file=sys.stderr)
        exit(1)
        return
    execve([
        "/usr/bin/gdb",
        "--ex", "target remote localhost:1234",
        "/opt/linux/vmlinux",
    ])


def logs():
    if os.path.exists("/tmp/kernel/kernel.log"):
        execve([
            "/usr/bin/tail",
            "-F",
            "-n+1",
            "/tmp/kernel/kernel.log",
        ])


def main():
    initialize()

    parser = argparse.ArgumentParser()
    subparsers = parser.add_subparsers(dest="command", required=True)
    connect_parser = subparsers.add_parser("connect", help="connect to kernel")
    start_parser = subparsers.add_parser("start", help="start kernel")
    stop_parser = subparsers.add_parser("stop", help="stop kernel")
    restart_parser = subparsers.add_parser("restart", help="restart kernel")
    debug_parser = subparsers.add_parser("debug", help="debug kernel")
    logs_parser = subparsers.add_parser("logs", help="show kernel logs")
    args = parser.parse_args()

    commands = {
        "connect": lambda: (start(), connect()),
        "start": lambda: start(),
        "stop": lambda: stop(),
        "restart": lambda: (stop(), start()),
        "debug": lambda: debug(),
        "logs": lambda: logs(),
    }

    try:
        commands[args.command]()
    except KeyboardInterrupt:
        pass


if __name__ == '__main__':
    main()
